; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -aarch64-enable-vector-reg-zeroing=true < %s | FileCheck %s --check-prefix=ZEROING
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -aarch64-enable-vector-reg-zeroing=false < %s | FileCheck %s --check-prefix=NO-ZEROING

; Test that unused caller-saved vector registers are zeroed before loops

; Function uses only Q0-Q2, so Q3-Q7 and Q16-Q31 should be zeroed
define void @test_simple_loop(ptr %a, ptr %b, i32 %n) {
; ZEROING-LABEL: test_simple_loop:
; ZEROING:       // %bb.0: // %entry
; ZEROING-NEXT:    cmp w2, #1
; ZEROING-NEXT:    b.lt .LBB0_3
; ZEROING-NEXT:  // %bb.1: // %loop.preheader
; ZEROING-NEXT:    mov x8, xzr
; ZEROING-NEXT:    movi v2.2d, #0000000000000000
; ZEROING-NEXT:    movi v3.2d, #0000000000000000
; ZEROING-NEXT:    movi v4.2d, #0000000000000000
; ZEROING-NEXT:    movi v5.2d, #0000000000000000
; ZEROING-NEXT:    movi v6.2d, #0000000000000000
; ZEROING-NEXT:    movi v7.2d, #0000000000000000
; ZEROING-NEXT:    movi v16.2d, #0000000000000000
; ZEROING-NEXT:    movi v17.2d, #0000000000000000
; ZEROING-NEXT:    movi v18.2d, #0000000000000000
; ZEROING-NEXT:    movi v19.2d, #0000000000000000
; ZEROING-NEXT:    movi v20.2d, #0000000000000000
; ZEROING-NEXT:    movi v21.2d, #0000000000000000
; ZEROING-NEXT:    movi v22.2d, #0000000000000000
; ZEROING-NEXT:    movi v23.2d, #0000000000000000
; ZEROING-NEXT:    movi v24.2d, #0000000000000000
; ZEROING-NEXT:    movi v25.2d, #0000000000000000
; ZEROING-NEXT:    movi v26.2d, #0000000000000000
; ZEROING-NEXT:    movi v27.2d, #0000000000000000
; ZEROING-NEXT:    movi v28.2d, #0000000000000000
; ZEROING-NEXT:    movi v29.2d, #0000000000000000
; ZEROING-NEXT:    movi v30.2d, #0000000000000000
; ZEROING-NEXT:    movi v31.2d, #0000000000000000
; ZEROING-NEXT:  .LBB0_2: // %loop
; ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; ZEROING-NEXT:    lsl x9, x8, #4
; ZEROING-NEXT:    add x8, x8, #1
; ZEROING-NEXT:    cmp w8, w2
; ZEROING-NEXT:    ldr q0, [x0, x9]
; ZEROING-NEXT:    ldr q1, [x1, x9]
; ZEROING-NEXT:    fadd v0.4s, v0.4s, v1.4s
; ZEROING-NEXT:    str q0, [x0, x9]
; ZEROING-NEXT:    b.lt .LBB0_2
; ZEROING-NEXT:  .LBB0_3: // %exit
; ZEROING-NEXT:    ret
;
; NO-ZEROING-LABEL: test_simple_loop:
; NO-ZEROING:       // %bb.0: // %entry
; NO-ZEROING-NEXT:    cmp w2, #1
; NO-ZEROING-NEXT:    b.lt .LBB0_3
; NO-ZEROING-NEXT:  // %bb.1: // %loop.preheader
; NO-ZEROING-NEXT:    mov x8, xzr
; NO-ZEROING-NEXT:  .LBB0_2: // %loop
; NO-ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; NO-ZEROING-NEXT:    lsl x9, x8, #4
; NO-ZEROING-NEXT:    add x8, x8, #1
; NO-ZEROING-NEXT:    cmp w8, w2
; NO-ZEROING-NEXT:    ldr q0, [x0, x9]
; NO-ZEROING-NEXT:    ldr q1, [x1, x9]
; NO-ZEROING-NEXT:    fadd v0.4s, v0.4s, v1.4s
; NO-ZEROING-NEXT:    str q0, [x0, x9]
; NO-ZEROING-NEXT:    b.lt .LBB0_2
; NO-ZEROING-NEXT:  .LBB0_3: // %exit
; NO-ZEROING-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop, label %exit

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %a.gep = getelementptr <4 x float>, ptr %a, i32 %i
  %b.gep = getelementptr <4 x float>, ptr %b, i32 %i
  %a.val = load <4 x float>, ptr %a.gep
  %b.val = load <4 x float>, ptr %b.gep
  %sum = fadd <4 x float> %a.val, %b.val
  store <4 x float> %sum, ptr %a.gep
  %i.next = add i32 %i, 1
  %cmp.loop = icmp slt i32 %i.next, %n
  br i1 %cmp.loop, label %loop, label %exit

exit:
  ret void
}

; Test that callee-saved registers Q8-Q15 are NOT zeroed
define void @test_callee_saved_not_zeroed(ptr %a, i32 %n) {
; ZEROING-LABEL: test_callee_saved_not_zeroed:
; ZEROING:       // %bb.0: // %entry
; ZEROING-NEXT:    cmp w1, #1
; ZEROING-NEXT:    b.lt .LBB1_3
; ZEROING-NEXT:  // %bb.1: // %loop.preheader
; ZEROING-NEXT:    mov x8, xzr
; ZEROING-NEXT:    movi v1.2d, #0000000000000000
; ZEROING-NEXT:    movi v2.2d, #0000000000000000
; ZEROING-NEXT:    movi v3.2d, #0000000000000000
; ZEROING-NEXT:    movi v4.2d, #0000000000000000
; ZEROING-NEXT:    movi v5.2d, #0000000000000000
; ZEROING-NEXT:    movi v6.2d, #0000000000000000
; ZEROING-NEXT:    movi v7.2d, #0000000000000000
; ZEROING-NEXT:    movi v16.2d, #0000000000000000
; ZEROING-NEXT:    movi v17.2d, #0000000000000000
; ZEROING-NEXT:    movi v18.2d, #0000000000000000
; ZEROING-NEXT:    movi v19.2d, #0000000000000000
; ZEROING-NEXT:    movi v20.2d, #0000000000000000
; ZEROING-NEXT:    movi v21.2d, #0000000000000000
; ZEROING-NEXT:    movi v22.2d, #0000000000000000
; ZEROING-NEXT:    movi v23.2d, #0000000000000000
; ZEROING-NEXT:    movi v24.2d, #0000000000000000
; ZEROING-NEXT:    movi v25.2d, #0000000000000000
; ZEROING-NEXT:    movi v26.2d, #0000000000000000
; ZEROING-NEXT:    movi v27.2d, #0000000000000000
; ZEROING-NEXT:    movi v28.2d, #0000000000000000
; ZEROING-NEXT:    movi v29.2d, #0000000000000000
; ZEROING-NEXT:    movi v30.2d, #0000000000000000
; ZEROING-NEXT:    movi v31.2d, #0000000000000000
; ZEROING-NEXT:  .LBB1_2: // %loop
; ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; ZEROING-NEXT:    lsl x9, x8, #4
; ZEROING-NEXT:    add x8, x8, #1
; ZEROING-NEXT:    cmp w8, w1
; ZEROING-NEXT:    ldr q0, [x0, x9]
; ZEROING-NEXT:    fadd v0.2d, v0.2d, v0.2d
; ZEROING-NEXT:    str q0, [x0, x9]
; ZEROING-NEXT:    b.lt .LBB1_2
; ZEROING-NEXT:  .LBB1_3: // %exit
; ZEROING-NEXT:    ret
;
; NO-ZEROING-LABEL: test_callee_saved_not_zeroed:
; NO-ZEROING:       // %bb.0: // %entry
; NO-ZEROING-NEXT:    cmp w1, #1
; NO-ZEROING-NEXT:    b.lt .LBB1_3
; NO-ZEROING-NEXT:  // %bb.1: // %loop.preheader
; NO-ZEROING-NEXT:    mov x8, xzr
; NO-ZEROING-NEXT:  .LBB1_2: // %loop
; NO-ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; NO-ZEROING-NEXT:    lsl x9, x8, #4
; NO-ZEROING-NEXT:    add x8, x8, #1
; NO-ZEROING-NEXT:    cmp w8, w1
; NO-ZEROING-NEXT:    ldr q0, [x0, x9]
; NO-ZEROING-NEXT:    fadd v0.2d, v0.2d, v0.2d
; NO-ZEROING-NEXT:    str q0, [x0, x9]
; NO-ZEROING-NEXT:    b.lt .LBB1_2
; NO-ZEROING-NEXT:  .LBB1_3: // %exit
; NO-ZEROING-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop, label %exit

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %a.gep = getelementptr <2 x double>, ptr %a, i32 %i
  %val = load <2 x double>, ptr %a.gep
  %mul = fmul <2 x double> %val, <double 2.0, double 2.0>
  store <2 x double> %mul, ptr %a.gep
  %i.next = add i32 %i, 1
  %cmp.loop = icmp slt i32 %i.next, %n
  br i1 %cmp.loop, label %loop, label %exit

exit:
  ret void
}

; Test that used registers are NOT zeroed
define void @test_used_registers_not_zeroed(ptr %a, ptr %b, ptr %c, i32 %n) {
; Uses Q0, Q1, Q2, Q3, Q4 - these should NOT be zeroed
; Q5-Q7, Q16-Q31 should be zeroed
; ZEROING-LABEL: test_used_registers_not_zeroed:
; ZEROING:       // %bb.0: // %entry
; ZEROING-NEXT:    cmp w3, #1
; ZEROING-NEXT:    b.lt .LBB2_3
; ZEROING-NEXT:  // %bb.1: // %loop.preheader
; ZEROING-NEXT:    mov x8, xzr
; ZEROING-NEXT:    movi v2.2d, #0000000000000000
; ZEROING-NEXT:    movi v3.2d, #0000000000000000
; ZEROING-NEXT:    movi v4.2d, #0000000000000000
; ZEROING-NEXT:    movi v5.2d, #0000000000000000
; ZEROING-NEXT:    movi v6.2d, #0000000000000000
; ZEROING-NEXT:    movi v7.2d, #0000000000000000
; ZEROING-NEXT:    movi v16.2d, #0000000000000000
; ZEROING-NEXT:    movi v17.2d, #0000000000000000
; ZEROING-NEXT:    movi v18.2d, #0000000000000000
; ZEROING-NEXT:    movi v19.2d, #0000000000000000
; ZEROING-NEXT:    movi v20.2d, #0000000000000000
; ZEROING-NEXT:    movi v21.2d, #0000000000000000
; ZEROING-NEXT:    movi v22.2d, #0000000000000000
; ZEROING-NEXT:    movi v23.2d, #0000000000000000
; ZEROING-NEXT:    movi v24.2d, #0000000000000000
; ZEROING-NEXT:    movi v25.2d, #0000000000000000
; ZEROING-NEXT:    movi v26.2d, #0000000000000000
; ZEROING-NEXT:    movi v27.2d, #0000000000000000
; ZEROING-NEXT:    movi v28.2d, #0000000000000000
; ZEROING-NEXT:    movi v29.2d, #0000000000000000
; ZEROING-NEXT:    movi v30.2d, #0000000000000000
; ZEROING-NEXT:    movi v31.2d, #0000000000000000
; ZEROING-NEXT:  .LBB2_2: // %loop
; ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; ZEROING-NEXT:    lsl x9, x8, #4
; ZEROING-NEXT:    add x8, x8, #1
; ZEROING-NEXT:    cmp w8, w3
; ZEROING-NEXT:    ldr q0, [x0, x9]
; ZEROING-NEXT:    ldr q1, [x1, x9]
; ZEROING-NEXT:    fmul v0.4s, v0.4s, v1.4s
; ZEROING-NEXT:    ldr q1, [x2, x9]
; ZEROING-NEXT:    fadd v0.4s, v0.4s, v1.4s
; ZEROING-NEXT:    str q0, [x0, x9]
; ZEROING-NEXT:    b.lt .LBB2_2
; ZEROING-NEXT:  .LBB2_3: // %exit
; ZEROING-NEXT:    ret
;
; NO-ZEROING-LABEL: test_used_registers_not_zeroed:
; NO-ZEROING:       // %bb.0: // %entry
; NO-ZEROING-NEXT:    cmp w3, #1
; NO-ZEROING-NEXT:    b.lt .LBB2_3
; NO-ZEROING-NEXT:  // %bb.1: // %loop.preheader
; NO-ZEROING-NEXT:    mov x8, xzr
; NO-ZEROING-NEXT:  .LBB2_2: // %loop
; NO-ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; NO-ZEROING-NEXT:    lsl x9, x8, #4
; NO-ZEROING-NEXT:    add x8, x8, #1
; NO-ZEROING-NEXT:    cmp w8, w3
; NO-ZEROING-NEXT:    ldr q0, [x0, x9]
; NO-ZEROING-NEXT:    ldr q1, [x1, x9]
; NO-ZEROING-NEXT:    fmul v0.4s, v0.4s, v1.4s
; NO-ZEROING-NEXT:    ldr q1, [x2, x9]
; NO-ZEROING-NEXT:    fadd v0.4s, v0.4s, v1.4s
; NO-ZEROING-NEXT:    str q0, [x0, x9]
; NO-ZEROING-NEXT:    b.lt .LBB2_2
; NO-ZEROING-NEXT:  .LBB2_3: // %exit
; NO-ZEROING-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop, label %exit

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %a.gep = getelementptr <4 x float>, ptr %a, i32 %i
  %b.gep = getelementptr <4 x float>, ptr %b, i32 %i
  %c.gep = getelementptr <4 x float>, ptr %c, i32 %i
  %a.val = load <4 x float>, ptr %a.gep
  %b.val = load <4 x float>, ptr %b.gep
  %c.val = load <4 x float>, ptr %c.gep
  %mul = fmul <4 x float> %a.val, %b.val
  %sum = fadd <4 x float> %mul, %c.val
  store <4 x float> %sum, ptr %a.gep
  %i.next = add i32 %i, 1
  %cmp.loop = icmp slt i32 %i.next, %n
  br i1 %cmp.loop, label %loop, label %exit

exit:
  ret void
}

; Test with subregs (D, S, H registers map to Q registers)
define void @test_subregs(ptr %a, i32 %n) {
; Uses D0 (maps to Q0), so Q0 should NOT be zeroed
; Q1-Q7, Q16-Q31 should be zeroed
; ZEROING-LABEL: test_subregs:
; ZEROING:       // %bb.0: // %entry
; ZEROING-NEXT:    cmp w1, #1
; ZEROING-NEXT:    b.lt .LBB3_3
; ZEROING-NEXT:  // %bb.1: // %loop.preheader
; ZEROING-NEXT:    mov x8, xzr
; ZEROING-NEXT:    movi v1.2d, #0000000000000000
; ZEROING-NEXT:    movi v2.2d, #0000000000000000
; ZEROING-NEXT:    movi v3.2d, #0000000000000000
; ZEROING-NEXT:    movi v4.2d, #0000000000000000
; ZEROING-NEXT:    movi v5.2d, #0000000000000000
; ZEROING-NEXT:    movi v6.2d, #0000000000000000
; ZEROING-NEXT:    movi v7.2d, #0000000000000000
; ZEROING-NEXT:    movi v16.2d, #0000000000000000
; ZEROING-NEXT:    movi v17.2d, #0000000000000000
; ZEROING-NEXT:    movi v18.2d, #0000000000000000
; ZEROING-NEXT:    movi v19.2d, #0000000000000000
; ZEROING-NEXT:    movi v20.2d, #0000000000000000
; ZEROING-NEXT:    movi v21.2d, #0000000000000000
; ZEROING-NEXT:    movi v22.2d, #0000000000000000
; ZEROING-NEXT:    movi v23.2d, #0000000000000000
; ZEROING-NEXT:    movi v24.2d, #0000000000000000
; ZEROING-NEXT:    movi v25.2d, #0000000000000000
; ZEROING-NEXT:    movi v26.2d, #0000000000000000
; ZEROING-NEXT:    movi v27.2d, #0000000000000000
; ZEROING-NEXT:    movi v28.2d, #0000000000000000
; ZEROING-NEXT:    movi v29.2d, #0000000000000000
; ZEROING-NEXT:    movi v30.2d, #0000000000000000
; ZEROING-NEXT:    movi v31.2d, #0000000000000000
; ZEROING-NEXT:  .LBB3_2: // %loop
; ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; ZEROING-NEXT:    ldr d0, [x0, x8, lsl #3]
; ZEROING-NEXT:    fadd d0, d0, d0
; ZEROING-NEXT:    str d0, [x0, x8, lsl #3]
; ZEROING-NEXT:    add x8, x8, #1
; ZEROING-NEXT:    cmp w8, w1
; ZEROING-NEXT:    b.lt .LBB3_2
; ZEROING-NEXT:  .LBB3_3: // %exit
; ZEROING-NEXT:    ret
;
; NO-ZEROING-LABEL: test_subregs:
; NO-ZEROING:       // %bb.0: // %entry
; NO-ZEROING-NEXT:    cmp w1, #1
; NO-ZEROING-NEXT:    b.lt .LBB3_3
; NO-ZEROING-NEXT:  // %bb.1: // %loop.preheader
; NO-ZEROING-NEXT:    mov x8, xzr
; NO-ZEROING-NEXT:  .LBB3_2: // %loop
; NO-ZEROING-NEXT:    // =>This Inner Loop Header: Depth=1
; NO-ZEROING-NEXT:    ldr d0, [x0, x8, lsl #3]
; NO-ZEROING-NEXT:    fadd d0, d0, d0
; NO-ZEROING-NEXT:    str d0, [x0, x8, lsl #3]
; NO-ZEROING-NEXT:    add x8, x8, #1
; NO-ZEROING-NEXT:    cmp w8, w1
; NO-ZEROING-NEXT:    b.lt .LBB3_2
; NO-ZEROING-NEXT:  .LBB3_3: // %exit
; NO-ZEROING-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop, label %exit

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %a.gep = getelementptr double, ptr %a, i32 %i
  %val = load double, ptr %a.gep
  %mul = fmul double %val, 2.0
  store double %mul, ptr %a.gep
  %i.next = add i32 %i, 1
  %cmp.loop = icmp slt i32 %i.next, %n
  br i1 %cmp.loop, label %loop, label %exit

exit:
  ret void
}

; Test that nested loops only get zeroing at the outermost loop
; The inner loop should NOT have zeroing instructions
define void @test_nested_loops(ptr %a, ptr %b, i32 %m, i32 %n) {
; ZEROING-LABEL: test_nested_loops:
; ZEROING:       // %bb.0: // %entry
; ZEROING-NEXT:    cmp w2, #1
; ZEROING-NEXT:    b.lt .LBB4_6
; ZEROING-NEXT:  // %bb.1: // %outer.loop.preheader
; ZEROING-NEXT:    mov w8, wzr
; ZEROING-NEXT:    movi v2.2d, #0000000000000000
; ZEROING-NEXT:    movi v3.2d, #0000000000000000
; ZEROING-NEXT:    movi v4.2d, #0000000000000000
; ZEROING-NEXT:    movi v5.2d, #0000000000000000
; ZEROING-NEXT:    movi v6.2d, #0000000000000000
; ZEROING-NEXT:    movi v7.2d, #0000000000000000
; ZEROING-NEXT:    movi v16.2d, #0000000000000000
; ZEROING-NEXT:    movi v17.2d, #0000000000000000
; ZEROING-NEXT:    movi v18.2d, #0000000000000000
; ZEROING-NEXT:    movi v19.2d, #0000000000000000
; ZEROING-NEXT:    movi v20.2d, #0000000000000000
; ZEROING-NEXT:    movi v21.2d, #0000000000000000
; ZEROING-NEXT:    movi v22.2d, #0000000000000000
; ZEROING-NEXT:    movi v23.2d, #0000000000000000
; ZEROING-NEXT:    movi v24.2d, #0000000000000000
; ZEROING-NEXT:    movi v25.2d, #0000000000000000
; ZEROING-NEXT:    movi v26.2d, #0000000000000000
; ZEROING-NEXT:    movi v27.2d, #0000000000000000
; ZEROING-NEXT:    movi v28.2d, #0000000000000000
; ZEROING-NEXT:    movi v29.2d, #0000000000000000
; ZEROING-NEXT:    movi v30.2d, #0000000000000000
; ZEROING-NEXT:    movi v31.2d, #0000000000000000
; ZEROING-NEXT:    b .LBB4_3
; ZEROING-NEXT:  .LBB4_2: // %outer.latch
; ZEROING-NEXT:    // in Loop: Header=BB4_3 Depth=1
; ZEROING-NEXT:    add w8, w8, #1
; ZEROING-NEXT:    cmp w8, w2
; ZEROING-NEXT:    b.ge .LBB4_6
; ZEROING-NEXT:  .LBB4_3: // %outer.loop
; ZEROING-NEXT:    // =>This Loop Header: Depth=1
; ZEROING-NEXT:    // Child Loop BB4_5 Depth 2
; ZEROING-NEXT:    cmp w3, #1
; ZEROING-NEXT:    b.lt .LBB4_2
; ZEROING-NEXT:  // %bb.4: // %inner.loop.preheader
; ZEROING-NEXT:    // in Loop: Header=BB4_3 Depth=1
; ZEROING-NEXT:    mov x9, xzr
; ZEROING-NEXT:  .LBB4_5: // %inner.loop
; ZEROING-NEXT:    // Parent Loop BB4_3 Depth=1
; ZEROING-NEXT:    // => This Inner Loop Header: Depth=2
; ZEROING-NEXT:    lsl x10, x9, #4
; ZEROING-NEXT:    add x9, x9, #1
; ZEROING-NEXT:    cmp w9, w3
; ZEROING-NEXT:    ldr q0, [x0, x10]
; ZEROING-NEXT:    ldr q1, [x1, x10]
; ZEROING-NEXT:    fadd v0.4s, v0.4s, v1.4s
; ZEROING-NEXT:    str q0, [x0, x10]
; ZEROING-NEXT:    b.lt .LBB4_5
; ZEROING-NEXT:    b .LBB4_2
; ZEROING-NEXT:  .LBB4_6: // %exit
; ZEROING-NEXT:    ret
;
; NO-ZEROING-LABEL: test_nested_loops:
; NO-ZEROING:       // %bb.0: // %entry
; NO-ZEROING-NEXT:    cmp w2, #1
; NO-ZEROING-NEXT:    b.lt .LBB4_6
; NO-ZEROING-NEXT:  // %bb.1: // %outer.loop.preheader
; NO-ZEROING-NEXT:    mov w8, wzr
; NO-ZEROING-NEXT:    b .LBB4_3
; NO-ZEROING-NEXT:  .LBB4_2: // %outer.latch
; NO-ZEROING-NEXT:    // in Loop: Header=BB4_3 Depth=1
; NO-ZEROING-NEXT:    add w8, w8, #1
; NO-ZEROING-NEXT:    cmp w8, w2
; NO-ZEROING-NEXT:    b.ge .LBB4_6
; NO-ZEROING-NEXT:  .LBB4_3: // %outer.loop
; NO-ZEROING-NEXT:    // =>This Loop Header: Depth=1
; NO-ZEROING-NEXT:    // Child Loop BB4_5 Depth 2
; NO-ZEROING-NEXT:    cmp w3, #1
; NO-ZEROING-NEXT:    b.lt .LBB4_2
; NO-ZEROING-NEXT:  // %bb.4: // %inner.loop.preheader
; NO-ZEROING-NEXT:    // in Loop: Header=BB4_3 Depth=1
; NO-ZEROING-NEXT:    mov x9, xzr
; NO-ZEROING-NEXT:  .LBB4_5: // %inner.loop
; NO-ZEROING-NEXT:    // Parent Loop BB4_3 Depth=1
; NO-ZEROING-NEXT:    // => This Inner Loop Header: Depth=2
; NO-ZEROING-NEXT:    lsl x10, x9, #4
; NO-ZEROING-NEXT:    add x9, x9, #1
; NO-ZEROING-NEXT:    cmp w9, w3
; NO-ZEROING-NEXT:    ldr q0, [x0, x10]
; NO-ZEROING-NEXT:    ldr q1, [x1, x10]
; NO-ZEROING-NEXT:    fadd v0.4s, v0.4s, v1.4s
; NO-ZEROING-NEXT:    str q0, [x0, x10]
; NO-ZEROING-NEXT:    b.lt .LBB4_5
; NO-ZEROING-NEXT:    b .LBB4_2
; NO-ZEROING-NEXT:  .LBB4_6: // %exit
; NO-ZEROING-NEXT:    ret
entry:
  %cmp.outer = icmp sgt i32 %m, 0
  br i1 %cmp.outer, label %outer.loop, label %exit

outer.loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %outer.latch ]
  %cmp.inner = icmp sgt i32 %n, 0
  br i1 %cmp.inner, label %inner.loop, label %outer.latch

inner.loop:
  %j = phi i32 [ 0, %outer.loop ], [ %j.next, %inner.loop ]
  %a.gep = getelementptr <4 x float>, ptr %a, i32 %j
  %b.gep = getelementptr <4 x float>, ptr %b, i32 %j
  %a.val = load <4 x float>, ptr %a.gep
  %b.val = load <4 x float>, ptr %b.gep
  %sum = fadd <4 x float> %a.val, %b.val
  store <4 x float> %sum, ptr %a.gep
  %j.next = add i32 %j, 1
  %cmp.inner.loop = icmp slt i32 %j.next, %n
  br i1 %cmp.inner.loop, label %inner.loop, label %outer.latch

outer.latch:
  %i.next = add i32 %i, 1
  %cmp.outer.loop = icmp slt i32 %i.next, %m
  br i1 %cmp.outer.loop, label %outer.loop, label %exit

exit:
  ret void
}
