; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck %s

; Tests for the WidenMaskArithmeticToVT optimization that keeps mask operations
; at the natural comparison width instead of narrowing to i16 and widening back.

;============================================================================
; POSITIVE CASES: Optimization applies, no xtn/sshll/ushll dance
;============================================================================

; Simple shuffle of SETCC - splat lane 2
define <4 x i32> @shuffle_setcc_splat(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: shuffle_setcc_splat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v2.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v2.4s, v2.s[2]
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %cmp = icmp slt <4 x i32> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

; Simple shuffle of SETCC - splat lane 0
define <4 x i32> @shuffle_setcc_lane0(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: shuffle_setcc_lane0:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v2.4s, v0.4s, v1.4s
; CHECK-NEXT:    dup v2.4s, v2.s[0]
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %cmp = icmp sgt <4 x i32> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 0, i32 0, i32 0, i32 0>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

; AND of two SETCCs, then shuffle
define <4 x i32> @shuffle_and_setcc(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c) {
; CHECK-LABEL: shuffle_and_setcc:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smin v3.4s, v0.4s, v2.4s
; CHECK-NEXT:    cmgt v1.4s, v3.4s, v1.4s
; CHECK-NEXT:    dup v1.4s, v1.s[1]
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
  %cmp1 = icmp sgt <4 x i32> %a, %b
  %cmp2 = icmp slt <4 x i32> %b, %c
  %and = and <4 x i1> %cmp1, %cmp2
  %splat = shufflevector <4 x i1> %and, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

; OR of two SETCCs, then shuffle
define <4 x i32> @shuffle_or_setcc(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c) {
; CHECK-LABEL: shuffle_or_setcc:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmeq v3.4s, v0.4s, v1.4s
; CHECK-NEXT:    cmeq v1.4s, v1.4s, v2.4s
; CHECK-NEXT:    orr v1.16b, v3.16b, v1.16b
; CHECK-NEXT:    dup v1.4s, v1.s[3]
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
  %cmp1 = icmp eq <4 x i32> %a, %b
  %cmp2 = icmp eq <4 x i32> %b, %c
  %or = or <4 x i1> %cmp1, %cmp2
  %splat = shufflevector <4 x i1> %or, <4 x i1> poison, <4 x i32> <i32 3, i32 3, i32 3, i32 3>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

; XOR of two SETCCs, then shuffle
define <4 x i32> @shuffle_xor_setcc(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c) {
; CHECK-LABEL: shuffle_xor_setcc:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v3.4s, v0.4s, v1.4s
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v2.4s
; CHECK-NEXT:    eor v1.16b, v3.16b, v1.16b
; CHECK-NEXT:    dup v1.4s, v1.s[2]
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
  %cmp1 = icmp sgt <4 x i32> %a, %b
  %cmp2 = icmp sgt <4 x i32> %b, %c
  %xor = xor <4 x i1> %cmp1, %cmp2
  %splat = shufflevector <4 x i1> %xor, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

; Nested: shuffle of OR of ANDs of SETCCs
define <4 x i32> @shuffle_nested_logic(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d) {
; CHECK-LABEL: shuffle_nested_logic:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v4.4s, v1.4s, v2.4s
; CHECK-NEXT:    cmgt v5.4s, v0.4s, v1.4s
; CHECK-NEXT:    cmgt v2.4s, v2.4s, v3.4s
; CHECK-NEXT:    cmgt v1.4s, v3.4s, v1.4s
; CHECK-NEXT:    and v4.16b, v5.16b, v4.16b
; CHECK-NEXT:    and v1.16b, v2.16b, v1.16b
; CHECK-NEXT:    orr v1.16b, v4.16b, v1.16b
; CHECK-NEXT:    dup v1.4s, v1.s[1]
; CHECK-NEXT:    bif v0.16b, v3.16b, v1.16b
; CHECK-NEXT:    ret
  %cmp1 = icmp sgt <4 x i32> %a, %b
  %cmp2 = icmp sgt <4 x i32> %b, %c
  %and1 = and <4 x i1> %cmp1, %cmp2
  %cmp3 = icmp sgt <4 x i32> %c, %d
  %cmp4 = icmp sgt <4 x i32> %d, %b
  %and2 = and <4 x i1> %cmp3, %cmp4
  %or = or <4 x i1> %and1, %and2
  %splat = shufflevector <4 x i1> %or, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %d
  ret <4 x i32> %sel
}

; Unsigned comparison
define <4 x i32> @shuffle_setcc_unsigned(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: shuffle_setcc_unsigned:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmhi v2.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v2.4s, v2.s[3]
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %cmp = icmp ult <4 x i32> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 3, i32 3, i32 3, i32 3>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

; Float comparison
define <4 x float> @shuffle_fcmp(<4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: shuffle_fcmp:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmgt v2.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v2.4s, v2.s[1]
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %cmp = fcmp olt <4 x float> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  %sel = select <4 x i1> %splat, <4 x float> %a, <4 x float> %b
  ret <4 x float> %sel
}

; Non-splat shuffle that's still optimizable
define <4 x i32> @shuffle_setcc_rev(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: shuffle_setcc_rev:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v2.4s, v0.4s, v1.4s
; CHECK-NEXT:    rev64 v2.4s, v2.4s
; CHECK-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %cmp = icmp sgt <4 x i32> %a, %b
  %rev = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
  %sel = select <4 x i1> %rev, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

; v2i64 comparison
define <2 x i64> @shuffle_setcc_v2i64(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: shuffle_setcc_v2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v2.2d, v0.2d, v1.2d
; CHECK-NEXT:    dup v2.2d, v2.d[0]
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %cmp = icmp sgt <2 x i64> %a, %b
  %splat = shufflevector <2 x i1> %cmp, <2 x i1> poison, <2 x i32> <i32 0, i32 0>
  %sel = select <2 x i1> %splat, <2 x i64> %a, <2 x i64> %b
  ret <2 x i64> %sel
}

;============================================================================
; NEGATIVE CASES: Optimization doesn't apply, falls back to trunc/ext
;============================================================================

; Mask from load - not a SETCC chain, must use extension
define <4 x i32> @mask_from_load(ptr %p, <4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: mask_from_load:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldrb w8, [x0]
; CHECK-NEXT:    ubfx w8, w8, #1, #1
; CHECK-NEXT:    dup v2.4h, w8
; CHECK-NEXT:    ushll v2.4s, v2.4h, #0
; CHECK-NEXT:    shl v2.4s, v2.4s, #31
; CHECK-NEXT:    cmlt v2.4s, v2.4s, #0
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %mask = load <4 x i1>, ptr %p
  %splat = shufflevector <4 x i1> %mask, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

; Mask from truncation of non-comparison - must use extension
define <4 x i32> @mask_from_trunc(<4 x i32> %x, <4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: mask_from_trunc:
; CHECK:       // %bb.0:
; CHECK-NEXT:    xtn v0.4h, v0.4s
; CHECK-NEXT:    dup v0.4h, v0.h[2]
; CHECK-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-NEXT:    shl v0.4s, v0.4s, #31
; CHECK-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-NEXT:    bsl v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %trunc = trunc <4 x i32> %x to <4 x i1>
  %splat = shufflevector <4 x i1> %trunc, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

; Mask from call - external source, must use extension
declare <4 x i1> @get_mask()
define <4 x i32> @mask_from_call(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: mask_from_call:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sub sp, sp, #48
; CHECK-NEXT:    str x30, [sp, #32] // 8-byte Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    stp q0, q1, [sp] // 32-byte Folded Spill
; CHECK-NEXT:    bl get_mask
; CHECK-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-NEXT:    ldp q2, q1, [sp] // 32-byte Folded Reload
; CHECK-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; CHECK-NEXT:    dup v0.4h, v0.h[0]
; CHECK-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-NEXT:    shl v0.4s, v0.4s, #31
; CHECK-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-NEXT:    bsl v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    add sp, sp, #48
; CHECK-NEXT:    ret
  %mask = call <4 x i1> @get_mask()
  %splat = shufflevector <4 x i1> %mask, <4 x i1> poison, <4 x i32> <i32 0, i32 0, i32 0, i32 0>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

; Mask from phi - DAG speculatively executes both branches and uses BIT/BIF
; to select, which still benefits from mask widening on each branch.
define <4 x i32> @mask_from_phi(i1 %cond, <4 x i32> %a, <4 x i32> %b, <4 x i32> %c) {
; CHECK-LABEL: mask_from_phi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    tst w0, #0x1
; CHECK-NEXT:    cmgt v3.4s, v0.4s, v1.4s
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v2.4s
; CHECK-NEXT:    csetm w8, ne
; CHECK-NEXT:    dup v4.4s, w8
; CHECK-NEXT:    bit v1.16b, v3.16b, v4.16b
; CHECK-NEXT:    dup v1.4s, v1.s[1]
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
entry:
  br i1 %cond, label %if.then, label %if.else

if.then:
  %cmp1 = icmp sgt <4 x i32> %a, %b
  br label %join

if.else:
  %cmp2 = icmp sgt <4 x i32> %b, %c
  br label %join

join:
  %mask = phi <4 x i1> [ %cmp1, %if.then ], [ %cmp2, %if.else ]
  %splat = shufflevector <4 x i1> %mask, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

; Add of i1 values is equivalent to XOR, so this still gets optimized
define <4 x i32> @mask_from_add_setcc(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c) {
; CHECK-LABEL: mask_from_add_setcc:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v3.4s, v0.4s, v1.4s
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v2.4s
; CHECK-NEXT:    eor v1.16b, v3.16b, v1.16b
; CHECK-NEXT:    dup v1.4s, v1.s[2]
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
  %cmp1 = icmp sgt <4 x i32> %a, %b
  %cmp2 = icmp sgt <4 x i32> %b, %c
  %add = add <4 x i1> %cmp1, %cmp2
  %splat = shufflevector <4 x i1> %add, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}
